# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vN7vOBBDOeevL-z2NrAIF6pO17Ja7Ma
"""

import torch
from diffusers import StableDiffusionPipeline
import gradio as gr

def generate_logo(description):
    try:
        # Load the Stable Diffusion model
        pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2")
        pipe.to("cuda" if torch.cuda.is_available() else "cpu")

        # Generate the image
        image = pipe(description).images[0]

        # Save and return the image
        img_path = "generated_logo.png"
        image.save(img_path)
        return img_path

    except Exception as e:
        return f"Error: {str(e)}"

# Create a Gradio interface
iface = gr.Interface(
    fn=generate_logo,
    inputs=gr.Textbox(label="Enter Brand Description", placeholder="E.g., Modern tech startup with focus on sustainability"),
    outputs=gr.Image(label="Generated Logo"),
    title="AI Logo Generator",
    description="Enter a description of your brand, and get a custom AI-generated logo using Hugging Face's Stable Diffusion model."
)

# Run the Gradio interface
iface.launch()

!pip install gradio gradio deploy